#!/bin/sh

# CONF_FILE setting was removed
if [ ! -z "$CONF_FILE" ]; then
    echo "CONF_FILE setting is no longer supported. opensearch.yml must be placed in the config directory and cannot be renamed."
    exit 1
fi

# fails to start without keystore
if [ ! -f "${OPENSEARCH_PATH_CONF}/opensearch.keystore" ]; then
    "${OPENSEARCH_HOME}/bin/opensearch-keystore" create
fi
